name: server
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  shelf: ^1.1.0


dev_dependencies:
  build_runner:
  build_web_compilers: 
  pedantic: ^1.9.0
